### ISSUE TITLE
Team leaders are displayed at team detail page only if they are jurors

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#114]
```
teamleaders = Jury.objects.filter(team=team)
```
However, at IPT2019 we expect a case when a TL has no Master degree, so he/she cannot be a juror.

**Comment by david2457** [comment]
Yes, this needs to be fixed and is quite important.
I would make this priority for the next edition if possible.
When entering participant details, is there an option for: is juror?

**Comment by nickkolok** [comment]
@david2457, no, there are two objects for a judging team leader: a Juror with a Team affiliation and a participant with "Team Leader" role (see also #12). For IPT2019, we did an import in the following way: everybody who is juror was imported only as a juror; all the others were imported as participants. So, the Ukrainian team leader who couldn't judge was not imported as a juror.

**Comment by david2457** [comment]
Ok, this should be mainly fixed when participants register themselves on IPT connect in the future, there will be a 'can be juror' field

**Comment by lysenko-nikolay** [comment]
> For IPT2019, we did an import in the following way: everybody who is juror was imported only as a juror; all the others were imported as participants. So, the Ukrainian team leader who couldn't judge was not imported as a juror.

i like this solution, this thread could be closed.

**Comment by nickkolok** [comment]
It is not a description of a solution. It is the description of the cause of the problem.
