### ISSUE TITLE
Apriori rejections

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#115]
Apriori (preventive) rejections are (hypothetical) rejections which teams declare before the first fight. It seems that an apriori rejection should be a separate model like `EternalRejection` or `TacticalRejection`, but linked to the team, not to the round.

Looks too django-ish for me :(

Obvious workaround - eternal rejections at first fight...

**Comment by david2457** [comment]
After the recent rule decision to have an extra tactical rejection in the first fight, I doubt the rejections will change very much for some time. Hence feel free to close this and work on some of the other ideas.

**Comment by david2457** [comment]
I think this will be closed if that is ok. The rules went a big change in 2019 edition which will probably remain so for a while.
