### ISSUE TITLE
If no pools, `/poolranking` should say about it

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#170]
For now, a `/poolranking` page for a tournament without pools looks like so:
![изображение](https://user-images.githubusercontent.com/5008131/58087254-d8a6da80-7bc8-11e9-8c56-32d195d05cf7.png)
However, there should be:
+ a message that there are no pools;
+ a link to the general ranking;
+ the semifinall ranking table (if it exists).

**Comment by Zudik** [comment]
Done e8793cc623ccbcb1e160c5b988f2e28e745ebd14
