### ISSUE TITLE
Invite new contributors

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#174]
@david2457 or @vbonvin, could you please add the following people to organization members:
@arolandi97
@Sebastian-Fava
@Zudik 
? The main purpose is to be able to assign issues to them; no write access to `dev` branch (or any other branches) is required.

**Comment by david2457** [comment]
I have invited them as members to the repo. I think this should accomplish this task.

**Comment by nickkolok** [comment]
@david2457 , thank you very much!
When all the invitations will be accepted, we will close the issue :)

**Comment by david2457** [comment]
They are getting an error when I try to invite them :(

**Comment by fandejuni** [comment]
I can comment and create issues, though I cannot assign myself to an issue

**Comment by arolandi97** [comment]
Everything works now
