### ISSUE TITLE
[FPT2017] Autocompletion of participants in the round admin panel when a team is selected

### ISSUE THREAD

**Issue by mhrz** [IPTnet/ipt_connect#18]

**Comment by mhrz** [comment]
Solved by Louis.

Le fichier participant_fill.js avait disparu.

Un update de participant_fill.js a été fait pour que ce soit compatible avec toutes les instances des tournois. 

Contenu ci-dessous : 

---
function get_model_name() {
    var pathArray = window.location.pathname.split( '/' );
    for(var i = 0 ; i+1 < pathArray.length ; i++ ) {
        if(pathArray[i] == "admin") {
            return pathArray[i+1];
        }
    }
    return "" ;
}

function fill_participant(team_id,field) {
    if (response_cache[team_id]) {
        $(field).html(response_cache[team_id]);
    } else {
        var model = get_model_name();
        if(model != "" ) {
            $.getJSON("/"+model+"/member_for_team", {team_id: team_id},
                  function(ret, textStatus) {
                      //var options = '<option value="" selected="selected">---------</option>';                                                               
                      var options = '';
                      for (var i in ret['res']) {
                          options += '<option value="' + ret['res'][i].id + '">'
                              + ret['res'][i].name + '</option>';
                      }
                      response_cache[team_id] = options;
                      $(field).html(options);
                  });
        }
    }
}

function defer() {
    if (window.jQuery)
        $(document).ready(function() {
            $("#id_opponent_team").change(function() { fill_participant($(this).val(),"#id_opponent"); });
            $("#id_reporter_team").change(function() { fill_participant($(this).val(),"#id_reporter"); });
            $("#id_reviewer_team").change(function() { fill_participant($(this).val(),"#id_reviewer"); });
        });
    else
        setTimeout(function() { defer() }, 50);
}

var response_cache = {};
defer();
--

Notes : 

  - une API qui permet d'obtenir la liste des gens d'une équipe. L'an
dernier ça passait par un appel à
https://connect.iptnet.info/IPT2016/member_for_team?team_id=TEAM_ID (et donc
il faut changer urls.py en conséquence et avoir un forms capable de
répondre.)

 - prévenir le modèle concerné qu'il doit charger ce fichier et donc
 ajouter :
      class Media:
                js = ('admin/js/participant_fill.js',)

 - changer participant_fill.js pour qu'il gère autant IPT2016 que
 FPT2017 (voire faire un truc super générique qui gère tout).

**Comment by mhrz** [comment]
JS script here: https://github.com/vbonvin/ipt_connect/commit/f5ae717cfe323bca2228df394302b7a86e96ae84

**Comment by nickkolok** [comment]
Seems to be a useful feature, but it isn't working for now.

**Comment by nickkolok** [comment]
As for now (IPT2018): on the server participants are filtered, but not if you open a round with a team already selected (in that case you have to re-select the team). On local version, no filtering is applied.

**Comment by david2457** [comment]
Ahh, I remember this issue. Would be nice to fix.
Thank you!
