### ISSUE TITLE
The site is not updated when the record is deleted

### ISSUE THREAD

**Issue by Zudik** [IPTnet/ipt_connect#206]
Before the removal 
![Снимок экрана от 2019-10-23 21-36-11](https://user-images.githubusercontent.com/48177952/67424467-d95ff480-f5de-11e9-8dbb-2c243c753ca8.png)
![Снимок экрана от 2019-10-23 21-38-33](https://user-images.githubusercontent.com/48177952/67424489-e0870280-f5de-11e9-8767-6a0dd606c3c2.png)
After
![Снимок экрана от 2019-10-23 21-50-44](https://user-images.githubusercontent.com/48177952/67424723-58552d00-f5df-11e9-99e2-a10b7007fe05.png)

**Comment by lysenko-nikolay** [comment]
do the results update after changing Jury's grade? It should work.

what do you call "record"? Because if it is a team, then of course no, in this case there could appear physics fights with 2 teams i.e.

**Comment by Zudik** [comment]
"record" is the last round of the random room
If I delete his ranking is not updated
If I change Jury's grade ranking is updated
