### ISSUE TITLE
Add a public display of the bonus points

### ISSUE THREAD

**Issue by mhrz** [IPTnet/ipt_connect#37]

**Comment by vbonvin** [comment]
Tomorrow

**Comment by david2457** [comment]
I would also like to add to the list to have the automatic addition of bonus points fixed if this is not difficult to do.

**Comment by vbonvin** [comment]
It is already automatic for PF of 3 teams. But I deactivated it for IPT2018 as some rounds had 4 teams.

What need to be done, actually, is to handle properly 4-team PFs

**Comment by david2457** [comment]
Hi, just checking if any progress has been made on this?
