### ISSUE TITLE
A field for the second reporter (coreporter)

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#53]
(splitting #32)
The rules allow to report a problem using two team members. They are sometimes called both reporters, sometimes a reporter and a coreporter, and sometimes both coreporters. It will be OK if they will be called `Reporter 1` and `Reporter 2` as well.
The fact that the report is presented by two people does not affect the resulting score. That score is calculated in the same way as for one reporter.

So, in interface like this: http://127.0.0.1:8000/admin/IPTdev/round/83/change/ there should be an optional field `Coreporter` or `Reporter 2` near existing `Reporter`.
![image](https://user-images.githubusercontent.com/5008131/38781669-7167b2da-40f1-11e8-9272-946ef0653d13.png)

There should be no additional score fields for the coreporter.

I'm not sure how should the quantity of points gathered be counted for coreporters (like that: http://127.0.0.1:8000/IPTdev/teams/Croatia/ ) be displayed. There are two possible ways:
a) To divide the gathered point between the coreporters
b) To display full score for every coreporter.

Way (b) is rather convoluting, because then the sum of scores would not be equal to team score.

**Comment by vbonvin** [comment]
Initially, the second reporter was more someone who was just going from slides to slides so the first reporter could focus on talking. But in the past years I have seen more and more presentations where the talk was split in two. Plus, the second reporter is a non-negligible advantage during the discussion.

So it make sense to give points to the second reporter. But one would like to avoid having always the same guy being second reporter for every problem presented (I don't recall if being second reporter falls into the twice-per-PF limit?) and ended up being first in the number of points.

One solution could be to ask the two reporter how they want to split the points (e.g. 25%/75%, 50/50, ...)

I will ping the LOC about it to know their opinion.

**Comment by Sebastian-Fava** [comment]
Hello all :)

First i need to point out that during last IOC meeting someone proposed to abolish this rule (i recall that Andreas was in favor of suppressing the second reporter), so there is a very slight possibility that this problem solves itself, i.e. better wait for their vote to avoid unnecessary work.

In case it doesn't i would simply add the field for the "co-reporter", which remains passive except two cases:
- when adding a fight it checks if the same person took the floor more than twice
- when giving the best reporter award, if there was a co-reporter during that fight -> add second name in the certificate. (this implies that the best reporter is given based on the single best presentation and not on the average, as we did this year)

**Comment by david2457** [comment]
As with Sebastian's comment.

**Comment by vbonvin** [comment]
> it would be great to have a repo with rules as code and issues/pullrequests as proposals, and, of course, discussions like this. Is there already such a repo?

Yes, it's the ExeCom private repo. Up to them to create a public repo to discuss the rules (ask @david2457 and @Sebastian-Fava directly)

**Comment by nickkolok** [comment]
In any case, there should be an option to switch coreporters on or off.

**Comment by david2457** [comment]
How about this, any progress?

**Comment by nickkolok** [comment]
Due to last changes in rules, the option should have 3 states:
a) no coreporter
b) coreporter is displayed (at least in admin interface) and saved, but gets no points (IPT2019-like)
c) coreporter is equal to reporter and both of them

Point (b) has good chances to be default for IPT2019. Do we need to display the coreporter publiclyat the round page or somewhere else?

Marking the issue as `IPT2019 - essential` for at least until your answer.

**Comment by david2457** [comment]
Displaying the co-reporter publically would be nice yes, but sounds kind of
complicated.
If not, do not worry, so long as it takes into account the point shared.

**Comment by Sebastian-Fava** [comment]
There is a rule limiting the presence of a single participant on stage to no more than two times (one for finals) during a single PF.
Previously when they were allowed to stay for the whole duration of the PF both acting as reporter and co-reporter counted as "being on stage", do you think it should still be like this even with now its presence limited to the presentation part?

Personally, I would think so, because it can still be seen as "taking the stage", even if for a limited time.

In which case @nickkolok there would be the need to add a participant-wise counter when filling reporter, co-reporter, opponent and reviewer fields which give an error if it becomes higher than 2.
Would that be possible?

**Comment by nickkolok** [comment]
@Sebastian-Fava , it's surely as possible as the whole #56.
The question is: where should the information about forbidden participants be displayed? On the page like https://connect.iptnet.info/IPT2017/rounds/39/ or somewhere in admin interface?

**Comment by Sebastian-Fava** [comment]
I was thinking more in the admin interface. Probably restricting the chairman from adding a participant/problem is not the most flexible option because it may happen he fills the form only after the fight and realizes too late of its mistake.

I would rather add a warning message, like a pop-up window, and/or a red filled background on the forbidden participant, whenever selecting an option which doesn't meet the requirements.
What do you think?

**Comment by vbonvin** [comment]
My two cents on the forbidden participant thing. It seems a bit overkill to implement it in the interface. This can happen only at during the 3rd (or 4th) PF or a round and will reset for the upcoming rounds, so there's no need to keep track of it from rounds to rounds. Plus,

- Having it working will require the chairman to enter the name of the participants taking the floor at the latest immediately after each fight, which will not necessarily be done.
- It is pretty easy to spot the "fraud" without any tools, just by paying attention to who takes the floor. If the chairman misses it, be sure that the other participants will not :p 
- For chairmen who have a lot of trouble recognizing faces, writing down the names of who takes the floor is a solid alternative.
