### ISSUE TITLE
Create rounds 2, 3, (4) automatically after creating the first round.

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#57]
(splitting #32)
When the first round of any fight is created and the roles in the first round are determined, then the roles of the teams in the rest rounds are also determined. The only problem is that it is not specified in the round interface, is the fight 3-team or 4-team, so manual creation of first round and automated creation of the rest doesn't seem to be a good solution. I suggest making a Fight Creation Wizard instead: an interface where the number of teams can be selected and then table is filled manually, and all the rounds are created automatically. The role matrix is:

for 3-team fight:
```
              | Round 1 | Round 2 | Round 3 |
--------------|---------|---------|---------|
select team 1 | Rep.    | Rev.    | Opp.    |
--------------|---------|---------|---------|
select team 2 | Opp.    | Rep.    | Rev.    |
--------------|---------|---------|---------|
select team 3 | Rev.    | Opp.    | Rep.    |
--------------|---------|---------|---------|
```
for 4-team fight:

```
              | Round 1 | Round 2 | Round 3 | Round 4 |
-------------------------------------------------------
select team 1 | Rep.    | Obs.    | Rev.    | Opp.    |
-------------------------------------------------------
select team 2 | Opp.    | Rep.    | Obs.    | Rev.    |
-------------------------------------------------------
select team 3 | Rev.    | Opp.    | Rep.    | Obs.    |
-------------------------------------------------------
```

(please correct me if I am wrong)

Moreover, the list of jurys should be copied from first round to all the rest rounds. Speaking more precisely, jury list should be the same for all the rounds inside one fight.

**Comment by vbonvin** [comment]
The fight creation wizard sounds like a good idea! I'd suggest doing it through a form accessible only to administrators, from the website.

**Comment by nickkolok** [comment]
There are two ways to implement the feature.

1. The simple way: just to add checkboxes "Create the next rounds if not yet", "Spread jury members to the next rounds" and "Observer team" (the latter is a separate topic to discuss) in Round admin panel. If such a checkboxes are checked, then on Round saving (it already has a custom handler) the checkboxes should be saved unchecked, but the desired actions should be performed (`get_or_create()` is your friend).

2. The beautiful way: to implement the wizard. Adding arbitrary number of Jurors looks like the main problem for this case.

**Comment by nickkolok** [comment]
Option 3. To add `Add next` links to the page of every round (near `Edit` links).
