### ISSUE TITLE
Limit the permissions of a chairman

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#68]
There should be at least 2 types of accounts which can edit the marks:
1. A chairman can edit only the marks in fights (rounds) which he has lead.
2. An admin can edit all the marks.

Is that so now? If no, the separation should be implemented. If `ipt-coonect` will be used  in other tournaments, then it's important to protect the data from occasional edits.

**Comment by mhrz** [comment]
What I usually do is to define a auth group with permission 'edit grades, rejections, rounds', for the specific tournament. That way all the chairmen on a specific tournament can edit all the rounds on the same tournament, and have no other rights; which is usually what we want since the grades checking is done by all the chairmen at the same time in the same room (usually).

This never generated any problem in the past.

**Comment by vbonvin** [comment]
What lies behind your question is if multiple instances of IPT-connect should share the same database and, thus, permission access. 

If so, then using group permission as Maxime suggest is the way to go. Note that you can also control who can access which page using the @user_passes_test decorator (as we currently use in the [views.py](https://github.com/vbonvin/ipt_connect/blob/master/ipt_connect/IPT2018/views.py) file); this can also serve as the private mode requested in #67.

That being said, I'm a bit afraid that having all the apps running on the same database might cause problems at some point. The code is not super solid and in the past, I had to rollback the database a few times. As long as we are not having two tournaments running at the same time that should be fine though - and I doubt this will happen soon.

**Comment by nickkolok** [comment]
>  That way all the chairmen on a specific tournament can edit all the rounds on the same tournament, and have no other rights; which is usually what we want since the grades checking is done by all the chairmen at the same time in the same room (usually).

Sounds sane, so the issue is resolved.
