### ISSUE TITLE
IPT connect for 2019

### ISSUE THREAD

**Issue by david2457** [IPTnet/ipt_connect#71]
Hi guys, @nickkolok @vbonvin 

So what features will be up and running for IPT 2019?
- Just so I know what non connect stuff we and the LOC need to prepare for.

When do we think the connect system will be ready to accept information about participants?

To give some timeline ideas and general information:
- The target for IPT 2019 is to have 21 teams
- The deadline for registration will be at the latest 30th of December 00:00GMT
- From the registration deadline, either teams will be able to register their details on IPT connect, or, if there is a preselection, accepted teams will enter their details from mid January.
- The general team size: up to 6 team members, 2 team leader + any number of guests per team

**Comment by vbonvin** [comment]
Hi,

I don't know what @nickkolok has been working on so far, I haven't seen any pull request for a while, but I know he forked the repository so he might be working on its own version - as far as I'm concerned, I haven't implemented any significant change from the 2018 version.

> When do we think the connect system will be ready to accept information about participants?

When you want, basically. One simply needs to create a new IPT-connect instance for the IPT 2019, and then start creating accounts for the team-leader so they can register their team members. 

What you need to sort out is where ipt-connect will be hosted. So far, it's on the private server of one of @mhrz friend. Would be good to move it on our own IPT server at some point, though.

**Comment by david2457** [comment]
Excellent, thank you!
I'll create a new issue for regarding the server hosting

**Comment by david2457** [comment]
Hi,

Just putting this for now (i'll ask LOC closer to the date for what info they want from participants), but we will want a field asking if they are masters or bachelor students - optional.

**Comment by nickkolok** [comment]
Any guidelines or any evidence on how the registration process goes?

**Comment by david2457** [comment]
Hi Nikolai,

What do you mean by evidence? If you mean example, see if you can have a
look at the 2018 section.

The registration will basically collect details needed by the host
university, this includes:
basic participant information (Date of birth, name, passport number etc)
Tshirt size
dietary requirements
Team member of which team
living preference (male or female)

I will actually ask the host what kind of data they will be after now.

**Comment by nickkolok** [comment]
Hi @david2457,

I mean the description of the registration process, which could be smth like this:

1. Admin generates logins and passwords for team leaders (description of the way to generate) which are sent to the teamleaders automatucally / by hand.

2. Each team leader goes to url ... and does the following: ...

**Comment by david2457** [comment]
Ah yes!

This is exactly the way it has been done before and how I imagine it should
be done again.

Thank you

**Comment by mhrz** [comment]
Yes, no pb.

**Comment by david2457** [comment]
I'll be posting soon an update/request for IPT 2019 edition to start. Keep tuned!

In the meantime, something related to the juror allocation, could we keep in mind to add possibility for:
"....a juror to add team affiliations which will be used to exclude jurors from judging those teams, besides the completely separate formal affiliation."

**Comment by david2457** [comment]
Information needed:
- First name (as on passport/ID)
- Middle name (as on passport/ID)
- Last name (as on passport/ID)
- University/institution affiliation
- Date of birth
- Team/country
- Position (i.e. team leader, guest or team member)
- Sex (M/F)
- T-shirt/jumper size (S/M/L/XL)
- Dietary requirement (e.g. Vegan, Halal, etc)
- Dorm gender preference (Mixed/Single sex/team only)
- Disability requirements

- Custom requirement/notes to organisers

Not to go live yet. To be filled by team captains. Running like last year, they should be given log in details.

**Comment by david2457** [comment]
Could we get this stage setup in the next week?

**Comment by david2457** [comment]
Updated fields:

First name (as on passport/ID)

Middle name (as on passport/ID)

Last name (as on passport/ID)

University/institution affiliation

Date of birth

Place and country of birth

Nationality

Passport/ID number (international or travel passport)

Team/country

Position (i.e. team leader, guest or team member)

Sex (M/F)

T-shirt size (S/M/L/XL/XXL)

Dietary requirements (drop down selection):
vegan 
vegetarian
no pork
gluten intolerant
lactose intolerant
cheese intolerant
allergies : 
wheat
dairy
mustard
soy
celery
sulphite
lupine
egg
mollusc
crustacean
sesame
groundnut
fish
nut
other :

Dorm gender preference (Mixed/Single sex/team only)

Disability requirements

Custom requirement/notes to organisers

**Comment by david2457** [comment]
Any updates on this?

**Comment by david2457** [comment]
Can we generate a mailing list for year based off of:
https://docs.google.com/spreadsheets/d/1NWTNNNKHWIIUcGPz7f3y--MRxwXN3Q9apMt1QHZVBmE/edit#gid=1684879639

**Comment by mhrz** [comment]
FYI: the document is accessible to everyone with the link+ everyone has access to the link since this github repo is public. Please remove it ASAP.

**Comment by mhrz** [comment]
For such matters, please use the private repo.

**Comment by mhrz** [comment]
(also, I'm currently creating the ML)

**Comment by david2457** [comment]
Just noticed that error :/

**Comment by mhrz** [comment]
I suggest you delete the doc + create a new one with the same content, in order to avoid any pb.

**Comment by mhrz** [comment]
+ edit your comment with the link

**Comment by david2457** [comment]
Done, thanks

**Comment by nickkolok** [comment]
Closing as redundant. All the private discussion on it has been moved to the private ExeCom repo; all the discussions on particular points are in separate issues.
