### ISSUE TITLE
Merging forked repos

### ISSUE THREAD

**Issue by vbonvin** [IPTnet/ipt_connect#74]
@ijustbsd @nickkolok ,

As far as I know, you two are the only ones actively working on ipt-connect. I think it is a bit odd that you work on your own forked version of the repository while the "official" one (this one) stays silent. 

Similarly, there's no real point of me owning the repo, since it's a public one and I'm not really active on it. At this stage, I'm confident that you will not break the code by doing crazy things so there's no need for me to validate your pull requests anymore.

Thus, I propose that we do the following:

- You pull request your most recent changes (the dockerization) on this repo.
- We create an "International Physicists' Tournament" organization on github
- I transfer this repo to the IPT organization
- We all register as contributors of the IPT organization and the ipt-connect repo

What do you think?

**Comment by nickkolok** [comment]
And what about the issue history? Will it be preserved?

**Comment by david2457** [comment]
I think this sounds good!
If you are comfortable with it Vivien and the two are happy with this transfer then go ahead.

Thanks

**Comment by vbonvin** [comment]
> And what about the issue history? Will it be preserved?

Yes, as for the commit history.

**Comment by vbonvin** [comment]
No objections then? If not, I'll transfer the repo by tomorrow.

**Comment by ijustbsd** [comment]
I think it's good idea! What about [vrn](https://github.com/ijustbsd/ipt_connect/tree/vrn) branch in my repo? Should I create new repo in organization for it?

**Comment by vbonvin** [comment]
I'd say that since it's for a specific tournament only, it makes sense to keep it as a fork of the official repo on your own account. But if you think of good reasons to move it to the IPTnet organization I'm all open to it :)
