### ISSUE TITLE
Refactoring: make version consistent

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#77]
In `parameters.py` there is `app_version` parameter which is `dev`, not `IPTdev`.
It is used in URL parsing.
However, the `clone-instance.sh` script replaces `IPTdev` with the desired name, so a hack was applied.

The solution is to make `app_version` usage consistent, i.e. make it `IPTdev` and fix all the usages of it.

**Comment by vbonvin** [comment]
That's a minor issue - the idea of having `app_version = dev` and not `IPTdev` is that we expected all our apps to be IPTsomethingsomething. Might not be true if national tournaments start to use the soft, though.

Feel free to choose the use you prefer - as long as the result is consistent across the app.

**Comment by nickkolok** [comment]
FPT uses ipt-connect, doesn't it? So, we already have the problem with national tournaments.

**Comment by vbonvin** [comment]
Yes it does, but I think they run on a forked version.

**Comment by nickkolok** [comment]
Requires #112 to be done first
