### ISSUE TITLE
New instance concept

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#80]
I suggest a new instance concept:

1. `master` branch contains only `IPTdev` instance. This rule will save our power from being splitted to editing many instances.

2. When a new instance (e.g. `IPT2019`) is needed, a cloning script (`./clone-instance.sh` as for now) is launched and the desired instance is cloned. Copying separate instances to the production server prevents most of backwards-compatibility problems: instances of former IPT's are being saved in the state they were during the tournaments.

3. Any new features are tried to be implemented under a flag (i.e. you can enable or disable them in `parameters.py`). If such an implementation is impossible (the feature is a breaking change or there is no time to implement the feature properly), then the feature is implemented in the corresponding branch.

Any objections in this?

The issue can be closed as soon as strong objections are claimed or (docs are wriiten and `master` is fast-forwarded to `dev`).

**Comment by vbonvin** [comment]
> master branch contains only IPTdev instance. This rule will save our power from being splitted to editing many instances.

I prefer to have master branch containing a stable instance (i.e. the last version used) and dev branch as where the new edits are made. This way, someone who wants to fork the code can do it safely from the master branch. However, if you want to get rid of previous versions (IPT2016, IPT2017,...) you can move them to their separate branch.

> When a new instance (e.g. IPT2019) is needed, a cloning script (./clone-instance.sh as for now) is launched and the desired instance is cloned. Copying separate instances to the production server prevents most of backwards-compatibility problems: instances of former IPT's are being saved in the state they were during the tournaments.

Agree. To match what I said above, clone-instance would clone the master branch, and we ourselves are responsible to merge dev branch to master when we know it's stable. Ideally, we should set-up continuous integration and tests on the dev branch

> Any new features are tried to be implemented under a flag (i.e. you can enable or disable them in parameters.py). If such an implementation is impossible (the feature is a breaking change or there is no time to implement the feature properly), then the feature is implemented in the corresponding branch.

That behaviour is superseded by the use of a dev branch separate from master, which is more recommended than using flags. If a features does not work you can still rollback to previous commits, and you can experiment new features in sub-branches of dev. The goal of this is to keep a master branch always completely clean of any dev features.

**Comment by nickkolok** [comment]
> The goal of this is to keep a master branch always completely clean of any dev features.

I agree completely. However, we need to track issues to be closed by commit messages. So, I suppose to switch the main github branch to `dev`.
I think we should write a recommendation to branch from master for those who wants 

And about flags... My life would be much easier if pools, semifinals and bonus points were all under their own separate flags!

> To match what I said above, `./clone-instance.sh` would clone the master branch

Well... no. The script is cloning any instance (starting from IPT2019, but maybe older instances can be successfully cloned, too) and it can be run from any branch (starting from commit 627120ba0759bb5286a082103d72dd4776eeb08d).

And how about giving me access to push to `dev` branch?

**Comment by vbonvin** [comment]
> I agree completely. However, we need to track issues to be closed by commit messages. So, I suppose to switch the main github branch to dev.

Yep, good point.

> And about flags... My life would be much easier if pools, semifinals and bonus points were all under their own separate flags!

Ahh, I understand your point - it's not about experimental buggy features but changes due to different rules in different tournaments. In this case yes, using flags to turn certain behaviours on or off is probably the simplest solution.

> The script is cloning any instance

Yes sorry, I meant instance, not branch. But the point is that only the master branch should have content worth cloning (IPT20XX are legacy branches and dev is experimental)

> And how about giving me access to push to dev branch?

Your are a contributor of the repo with write access now so it should work.

**Comment by nickkolok** [comment]
@vbonvin , how about changing the default branch to `dev` here?
https://github.com/IPTnet/ipt_connect/settings/branches
I have no appropriate access.

It will allow us to close issues by commit messages.

**Comment by vbonvin** [comment]
Done.

I made you admin of the repo, so you should be able to do these things yourself from now :)
