### ISSUE TITLE
How should  semifinal bonus points be displayed?

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#94]
We have (or will have in the nearest future) bonus points publicly displayed on the team detail page like that: https://connect.iptnet.info/IPT2018/teams/Greece/

Current status (local development version):
![изображение](https://user-images.githubusercontent.com/5008131/54872211-a435be80-4dd1-11e9-928c-0cb19dc77b84.png)

The amount of bonus points is defined as sum of global manual bonus points (if enabled, they are edited in team editing interface) and sum of bonus points gathered in each selective fight. There are no bonus points in the final (they are redundant); so, the problem is: should we sum the semifinal bonus points up into the publicly displayed quantity?

We have three options:
a) Sum semifinal bonuses up into this amount
b) Don't display the semifinal bonuses publicly
c) Display separate quantities for selective fights and for semifinals

What's your opinion, comrads?

**Comment by vbonvin** [comment]
It depends on how the semifinalists are promoted to the final. If there are two semifinals, whose winners go to the final automatically and the runner-ups compete with each other for the 3rd seat, then having bonus points in the semifinals is redundant as well (@david2457 ?)

In case semifinal bonus points are important, I'd vote for your option c)

**Comment by nickkolok** [comment]
As the rules [state](https://github.com/vbonvin/IPT-execom/commit/d22ab32073ba51e6258b2b48e13c8a5960663272#diff-9dc1643fa3f8229ea98b473270f81acfR322), the team with 1st rank for selective fights is promoted to the final automatically; the rest two seats in the final are given to the teams with 1st and 2nd semifinal ranks. As far as semifinals are constructed as 2-5-6 and 3-4-7, the bonus points are not redundant.

**Comment by david2457** [comment]
Your interpretation is correct Nickolai!

**Comment by vbonvin** [comment]
Ok I see, and the points from the qualifying PF carry over the semifinals. Well, I'd still opt for c). 

Related to this but with a broader scope, do you want the score of the four qualifying PF to be separate from the rest (i.e. a page with the scores updated after semifinals are played) ?

**Comment by lysenko-nikolay** [comment]
1. **None**  of the bonus points in the semifinals should be displayed before the final PF.
2. I definitely vote for c) choice, because on this case anyone could see how many bonuses team obtained in each PF.
And I'd prefer not to eliminate 0-s:
2 + 1 + 0 +1 + 1.

**Comment by nickkolok** [comment]
@vbonvin,
> Related to this but with a broader scope, do you want the score of the four qualifying PF to be separate from the rest (i.e. a page with the scores updated after semifinals are played) ?

That was how semifinal ranking used to work in 2018, wasn't it? Planning to backport it :)

**Comment by nickkolok** [comment]
@lysenko-nikolay,
1. This should be something related to #96 . Of course, I can implement what you say literally, but I doubt if it will work sanely :)

2. Will displaying bonus points in fight summaries do that work?)

**Comment by lysenko-nikolay** [comment]
Yes, go to [#96](https://github.com/IPTnet/ipt_connect/issues/96)

2 - No, in this case you have to visit all PF pages on order to find out all team's bonuses. 
If, for instance, some sponsor of a team wants to see how their "investing" work they have to do the same. As I think it is not convenient for majority. Plus it is just too long.

**Comment by nickkolok** [comment]
If a sponsor wants to get a brief impression on the team, then info about rank and score  will be enough. If the sponsor is doing a more thorough investigation, he should explore each fight, analyze scores of each team member etc. - in any case this is a lot of work!

Why do we pay special attention to bonus points?

**Comment by david2457** [comment]
Maybe we can do it manually for now if it is too much trouble to make the
semifinal calculation unique to the main PF fights?

**Comment by nickkolok** [comment]
@david2457 , there is no problem to calculate semifinal ranking with double bonus points. The discussion is (was) on how to display the bonus points on team detail page.

So, if no objections - option (c) to be implemented.

**Comment by david2457** [comment]
no objections

**Comment by david2457** [comment]
This has been implemented, this can be closed
