### ISSUE TITLE
Pauses before and after the final

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#96]
If I remember right, the results of the final were not displayed directly after the end of the fight; they were kept in secret somehow.
However, for now ipt_connect displays all the results immediately.

Should we do something on that?

**Comment by lysenko-nikolay** [comment]
Moreover, results after semifinals (or 4 PF in case of small n of teams) have to be hidden also. Intrigue, drama...

This could be solved as in previous years: for this time all the pages on iptconnect/2019 are redirected to the page with .gif.

Another solution that I see is just turning off iptconnect as a whole.

**Comment by nickkolok** [comment]
Counter-argument: Important moments - such as promoting teams to the (semi)finals and (probably) computing final scores - should be made as transparent as possible. Chairmen may make mistakes. Coders may make mistakes. No one is guaranteed to make no mistakes. So, participants should be able to check everything.

**Comment by mhrz** [comment]
Yes, there should exist the possibility to hide easily the results in order for the org to check the results and spread the results when wanted.

**Comment by nickkolok** [comment]
@mhrz Do I understand right that such toggling of visibility was done manually  by editing `ninja_mode` variable in the code?

**Comment by mhrz** [comment]
Yep :)

**Comment by mhrz** [comment]
Implemented by @xuod :)

**Comment by nickkolok** [comment]
Were there any attempts to implement GUI for this? AFAIK, django has certain issues with singletons to contain settings...

**Comment by mhrz** [comment]
I don't think so. I'll let @xuod answer! But a possibility to activate/deactivate via the admin panel would be a GREAT help!

**Comment by lysenko-nikolay** [comment]
So, as Maxime confirmed, results should be easily hidden while semifinals.

**Comment by nickkolok** [comment]
Looks like these things could lead to the solution:
https://github.com/gbezyuk/django-solo-grappelli
https://github.com/lazybird/django-solo

AFAIK, first option is grappelli-friendly; no direct info on the second.

**Comment by david2457** [comment]
You have successfully implemented a GUI to activate/deactivate the ninja mode.
It was very useful, thank you very much!

**Comment by mhrz** [comment]
How to access it?

**Comment by david2457** [comment]
Ninja mode is available to super users.
It is on site configuration, once there, only a check box to activate and
deactivate

**Comment by mhrz** [comment]
Ah yes, I see it! Cool!
